[project]
name = "chestparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=5.5",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pathlib>=1.0.1",
    "pyside6>=6.8.2.1",
]
